app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
 * Route d'authentification et d'inscription
 */
Route::auth();

/*
 * Route de la page d'accueil
 */
Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);

/*
 * Route authentifié
 */
Route::group(['middleware' => 'auth'], function () {
    /*
     * Route du chat utilisateur
     */
    Route::group(['middleware' => 'role:admin|chat'], function () {
        Route::get('/chat', ['uses' => 'ChatController@index', 'as' => 'chat.index']);
        Route::post('/chat', ['uses' => 'ChatController@create', 'as' => 'chat.add']);
    });

    /*
     * Route du forum utilisateur
     */
    Route::group(['middleware' => 'role:admin|forum'], function () {
        Route::resource('post', 'PostController');
    });
    Route::group(['middleware' => 'role:admin|forum'], function () {
        Route::resource('comment', 'CommentController');
    });

    /*
     * Route des news utilisateur
     */
    Route::group(['middleware' => 'role:admin|news'], function () {
        Route::resource('news','NewsController');
    });

    /*
     * Route de l'administration
     */
    Route::group(['middleware' => 'role:admin', 'prefix' => 'admin'], function () {
        /*
         * Route des configurations
         */
        Route::get('config', ['uses' => 'Administration\ConfigController@index', 'as' => 'admin.config.index']);
        Route::get('config/edit', ['uses' => 'Administration\ConfigController@edit', 'as' => 'admin.config.modify']);
        Route::post('config/{id}/edit', ['uses' => 'Administration\ConfigController@update', 'as' => 'admin.config.update']);
        Route::post('config', ['uses' => 'Administration\ConfigController@create', 'as' => 'admin.config.create']);

        /*
         * Route des news
         */
        Route::get('news', ['uses' => 'Administration\NewsController@index', 'as' => 'admin.news.index']);
        Route::get('news/edit', ['uses' => 'Administration\NewsController@edit', 'as' => 'admin.news.modify']);
        Route::post('news/{id}/edit', ['uses' => 'Administration\NewsController@update', 'as' => 'admin.news.update']);
        Route::post('news', ['uses' => 'Administration\NewsController@create', 'as' => 'admin.news.create']);

        /*
         * Route du forum
         */
        Route::resource('forum', 'Administration\ForumController');

        /*
         * Route de gestion des utilisateurs
         */
        Route::resource('users', 'Administration\UsersController');
    });
});


/*
 * Injection des varriables Config et size_content dans les vues
 */
View::composer('*', function($view)
{
    $tmp = [];
    foreach (\App\Config::all() as $row) {
        $tmp[$row->key] = $row->value;
    }
    $view->with('Config', $tmp);

    $result = 6;
    if ($tmp['menu_gauche'] != 'true')
        $result += 3;
    if ($tmp['menu_droite'] != 'true')
        $result += 3;
    $view->with('size_content', $result);
});

app/Http/Controllers/Administration/ConfigController.php
<?php

namespace App\Http\Controllers\Administration;

use App\Config;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Laracasts\Flash\Flash;
use Zofe\Rapyd\Facades\DataGrid;

class ConfigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $grid = DataGrid::source(new Config);

        $grid->add('id','ID', true)->style("width:100px");
        $grid->add('key','Key');
        $grid->add('value','Value');



        $grid->edit(url('/admin/config/edit'), 'Edit','modify');
        $grid->orderBy('id','asc');
        $grid->paginate(10);

        $grid->row(function ($row) {
            if ($row->cell('id')->value == 20) {
                $row->style("background-color:#CCFF66");
            } elseif ($row->cell('id')->value > 15) {
                $row->cell('title')->style("font-weight:bold");
                $row->style("color:#f00");
            }
        });

        return  view('administration.config.index', compact('grid'));
    }

    /**
     * Save the new configuration
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $rules = [
            'key' => 'required',
            'value' => 'required'
        ];

        $validator = Validator::make(Input::all(), $rules);

        // process the login
        if ($validator->fails()) {
            Flash::error('Les champs ne sont pas correctement remplis.');
            return Redirect::route('admin.config.index')
                ->withErrors($validator);
        }else{
            // sauvegarde l'enregistrement
            $config = new Config();
            $config->key = $request->input('key');
            $config->value = $request->input('value');
            $config->save();

            Flash::success('Configuration bien ajoutée.');
        }

        return Redirect::route('admin.config.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        if (isset($_GET['modify'])) {
            $config = Config::findOrFail($_GET['modify']);
            return view('administration.config.modify', compact(['config'])) ;
        } else if (isset($_GET['delete'])) {
            Config::destroy($_GET['delete']);
            return Redirect::route('admin.config.index');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $config = Config::findOrFail($id);
        //$config->key = $request->input('key');
        $config->value = $request->input('value');
        $config->save();
        Flash::success('Configuration bien modifiée!');
        return Redirect::route('admin.config.index');
    }

}

app/Http/Controllers/Administration/ForumController.php
<?php

namespace App\Http\Controllers\Administration;

use App\Post;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Laracasts\Flash\Flash;

class ForumController extends Controller
{
    public function index() {
        $posts = Post::all();
        return view('administration.forum.index', compact(['posts']));
    }

    public function store(Request $request) {
        $rules = [
            'title'       => 'required|min:4|max:255',
            'content'      => 'required|min:15|max:500',
        ];

        $validator = Validator::make(Input::all(), $rules);

        // process the login
        if ($validator->fails()) {
            Flash::error('Les champs ne sont pas correctement remplis.');
            return Redirect::route('admin.forum.create')
                ->withErrors($validator);
        } else {
            // sauvegarde l'enregistrement
            $post = new Post();
            $post->title = $request->input('title');
            $post->content = $request->input('content');
            $post->userid = Auth::user()->id;
            $post->save();

            Flash::success('Post bien ajouté.');
            return Redirect::route('admin.forum.index');
        }
    }

    public function create(Request $request) {
        return view('administration.forum.create');
    }

    public function show($id) {
        // get the nerd
        $post = Post::findOrFail($id);

        // show the view and pass the nerd to it
        return view('administration.forum.show', compact(['post']));
    }

    public function edit($id) {
        $post = Post::findOrFail($id);
        return view('administration.forum.edit', compact(['post']));

    }

    public function update(Request $request, $id) {
        $rules = [
            'title'       => 'required|min:4|max:255',
            'content'      => 'required|min:15|max:500',
        ];

        // $messages = [
        //     'title.required' => 'Vous devez mettre un titre.',
        //     'title.between' => 'Votre :attribute doit faire entre :min et :max caractères',
        //     'title.min' => 'Votre :attribute doit faire au minimum :min caractères',
        //     'content.required' => 'Vous devez mettre un :attribute',
        //     'content.between' => 'Votre :attribute doit faire entre :min et :max caractères',
        //     'content.min' => 'Votre :attribute doit faire au minimum :min caractères',
        // ];

        $validator = Validator::make(Input::all(), $rules);

        // process the login
        if ($validator->fails()) {
            Flash::error('Les champs ne sont pas correctement remplis.');
            return Redirect::route('admin.forum.edit', $id)
                ->withErrors($validator);
        } else {
            // sauvegarde l'enregistrement
            $post = Post::findOrFail($id);
            $post->title = Input::get('title');
            $post->content = Input::get('content');
            $post->save();
            Flash::success('Post bien modifié.');
        }
        return Redirect::route('admin.forum.index');
    }

    public function destroy($id) {
        Post::destroy($id);

        // redirect
        Flash::success('Le post a bien été supprimé.');
        return Redirect::route('admin.forum.index');
    }
}

app/Http/Controllers/Administration/NewsController.php
<?php

namespace App\Http\Controllers\Administration;

use App\News;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Laracasts\Flash\Flash;
use Zofe\Rapyd\Facades\DataGrid;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $grid = DataGrid::source(News::with('user'));

        $grid->add('id','ID', true)->style("width:100px");
        $grid->add('titre','Titre');
        $grid->add('{{ substr($contenu,0,20) }}...','Contenu');
        $grid->add('user.name','Creator');

        $grid->edit(url('/admin/news/edit'), 'Edit','modify|delete|show');
        $grid->orderBy('id','asc');
        $grid->paginate(10);

        $grid->row(function ($row) {
            if ($row->cell('id')->value == 20) {
                $row->style("background-color:#CCFF66");
            } elseif ($row->cell('id')->value > 15) {
                $row->cell('title')->style("font-weight:bold");
                $row->style("color:#f00");
            }
        });

        return  view('administration.news.index', compact('grid'));
    }

    /**
     * Save the new configuration
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $rules = [
            'titre' => 'required',
            'contenu' => 'required'
        ];

        $validator = Validator::make(Input::all(), $rules);

        // process the login
        if ($validator->fails()) {
            Flash::error('Les champs ne sont pas correctement remplis.');
            return Redirect::route('admin.news.index')
                ->withErrors($validator);
        }else{
            // sauvegarde l'enregistrement
            $news = new News();
            $news->titre = $request->input('titre');
            $news->contenu = $request->input('contenu');
            $news->userid = Auth::user()->id;
            $news->save();

            Flash::success('News bien ajoutée.');
        }

        return Redirect::route('admin.news.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        if (isset($_GET['modify'])) {
            $news = News::findOrFail($_GET['modify']);
            return view('administration.news.modify', compact(['news'])) ;
        } else if (isset($_GET['delete'])) {
            News::destroy($_GET['delete']);
            return Redirect::route('admin.news.index');
        } else if (isset($_GET['show'])) {
            return Redirect::route('news.show', [$_GET['show']]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $news = News::findOrFail($id);
        $news->titre = $request->input('titre');
        $news->contenu = $request->input('contenu');
        $news->save();
        Flash::success('News bien modifiée!');
        return Redirect::route('admin.news.index');
    }
}

app/Http/Controllers/Administration/UsersController.php
<?php

namespace App\Http\Controllers\Administration;

use App\Role;
use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Laracasts\Flash\Flash;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('administration.users.index', compact(['users']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all();
        return view('administration.users.edit', compact(['user', 'roles']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->name = $request->input('name');
        $user->email = $request->input('email');

        $roleadmin = Role::findOrFail(1);
        $rolechat = Role::findOrFail(2);
        $roleforum = Role::findOrFail(3);
        $rolenews = Role::findOrFail(4);
        if ($request->input('admin')) {
            if (!$user->hasRole('admin'))
                $user->attachRole($roleadmin);
        } else {
            if ($user->hasRole('admin'))
                $user->detachRole($roleadmin);
        }

        if ($request->input('chat')) {
            if (!$user->hasRole('chat'))
                $user->attachRole($rolechat);
        } else {
            if ($user->hasRole('chat'))
                $user->detachRole($rolechat);
        }

        if ($request->input('forum')) {
            if (!$user->hasRole('forum'))
                $user->attachRole($roleforum);
        } else {
            if ($user->hasRole('forum'))
                $user->detachRole($roleforum);
        }

        if ($request->input('news')) {
            if (!$user->hasRole('news'))
                $user->attachRole($rolenews);
        } else {
            if ($user->hasRole('news'))
                $user->detachRole($rolenews);
        }

        $user->save();
        Flash::success('Utilisateur bien modifiée!');
        return Redirect::route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return Redirect::route('admin.users.index');
    }
}

resources/views/administration/forum/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading"><h1 style="font-size:22px; line-height:22px; margin: 0;padding:0;">Administration du Forum</h1></div>
        <div class="panel-body">
            Créez votre post
            <div class="send">

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        {{ HTML::ul($errors->all()) }}
                    </div>
                @endif

                {{ Form::open(['route' => 'admin.forum.store']) }}

                {{ Form::label('Titre', 'Titre du post') }}
                {{ Form::text('title', '', ['class' => 'form-control', 'minlength'=> '5', 'maxlength' => '155' ]) }}

                {{ Form::label('Contenu', 'Contenu du post') }}
                {{ Form::textarea('content', '', ['class' => 'form-control', 'minlength'=> '15', 'maxlength' => '1500' ]) }}

                {{ Form::submit('Envoyer', ['class' => 'btn btn-primary']) }}
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/administration/forum/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading"><h1 style="font-size:22px; line-height:22px; margin: 0;padding:0;">Administration du Forum</h1></div>
        <div class="panel-body">
            Modifier le post
            <div class="send">

                @if (count($errors) > 0)
                <div class="alert alert-danger">
                {{ HTML::ul($errors->all()) }}
                </div>
                @endif

                {{ Form::model($post, ['route' => ['admin.forum.update', $post->id], 'method' => 'PUT']) }}
                <div class="form-group">
                {{ Form::label('Titre', 'Titre du post') }}
                {{ Form::text('title', null, ['class' => 'form-control', 'minlength'=> '5', 'maxlength' => '155']) }}
                </div>
                <div class="form-group">
                {{ Form::label('Contenu', 'Contenu du post') }}
                {{ Form::textarea('content', null, ['class' => 'form-control', 'minlength'=> '15', 'maxlength' => '1500']) }}
                </div>
                {{ Form::submit('Envoyer', ['class' => 'btn btn-primary']) }}
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/administration/forum/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading"><h1 style="font-size:22px; line-height:22px; margin: 0;padding:0;">Administration du Forum</h1></div>
        <div class="panel-body">
            <div class="post">
                <table class="table">
                    <tr>
                        <th>Titre du post</th>
                        <th>Créé par</th>
                        <th>Date de création</th>
                        <th>Actions</th>
                    </tr>
                    @foreach($posts as $post)
                        <tr>
                            <td>{{ link_to_route('post.show', $post->title, ['id' => $post->id], ['class' => '']) }}</td>
                            <td>{{ $post->user->name }}</td>
                            <td>{{ $post->created_at }}</td>
                            <td>
                                    {{ link_to_route('admin.forum.edit','Éditer', ['id' => $post->id], ['style' => 'float: left; margin-right: 10px;', 'class' => 'btn btn-warning']) }}
                                    {{ Form::model($post, ['route' => ['admin.forum.destroy', $post->id], 'method' => 'DELETE']) }}
                                    {{ Form::submit('Supprimer', ['class' => 'btn btn-danger']) }}
                                    {{ Form::close() }}
                            </td>
                        </tr>
                    @endforeach
                </table>
                {{ link_to_route('admin.forum.create','Ajouter un post', [], ['class' => 'btn btn-primary']) }}
            </div>
        </div>
    </div>
@endsection

resources/views/administration/forum/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="panel panel-default">
		<div class="panel-heading">Administration du Forum</div>
		<div class="panel-body">
			<div class="show">
				<h2>{{ $post->title }}</h2>
				<div style="background-color: whitesmoke; padding: 10px; border: 1px solid rgba(0, 0, 0, 0.15); border-radius: 3px; margin: 20px 10px 10px;">
					<p>{{ $post->content }}</p>
				</div>
				<p>Par <i>{{ $post->user->name }}</i> le <i>{{ $post->created_at }}</i></p>
			</div>
		</div>
	</div>
@endsection